### ISSUE TITLE
Exception when saving layout or snippet after edit

### ISSUE THREAD

**Issue by kerryb** [jgarber/radiant-chronicle-extension#36]
After installing the extension on a clean Radiant 0.8 app, I get an error when saving layouts or snippets. Creating them is fine, but then when I edit and resave (even with no changes), I get this:

NoMethodError (undefined method `[]' for nil:NilClass):
 vendor/extensions/chronicle/lib/chronicle/resource_controller_extensions.rb:11:in`load_model'
 radiant (0.8.0) vendor/plugins/haml/rails/./lib/sass/plugin/rails.rb:19:in `process'

The error for layouts is similar. No problem with pages.

**Comment by kerryb** [comment]
Changing params["page"]... to params[model_class.name.underscore]... in resource_controller_extensions.rb seems to have fixed it.

Also, I had to create an extra migration to set the status of existing snippets and pages:

Snippet.update_all('status_id = 100')
Layout.update_all('status_id = 100')

**Comment by ehaselwanter** [comment]
I think this is fixed in the radiant fork

**Comment by jgarber** [comment]
Yes, I believe Sean Cribbs fixed this with 913de481.  Let me know if not fixed.
